on : push
name : 🚀 Implantar website em
jobs push :
  web-deploy :
    name : 🎉 Implementar
    runs-on : ubuntu-latest
    steps :
      - nome : 🚚 Obtenha os
        usos mais recentes do código : actions / checkout @ v2

      - nome : 📂 Os arquivos de sincronização
        usam : SamKirkland/FTP-Deploy-Action@4.1.0
        com :
          servidor : rush.granddns.info
          nome de usuário : aqbarhch
          senha : sjY[5Yf5h(E67V
          server-dir: /home6/aqbarhch/public_html/