on : push
name : 🚀 Implantar website em
jobs push :
  web-deploy :
    name : 🎉 Implementar
    runs-on : ubuntu-latest
    steps :
      - nome : 🚚 Obtenha os
        usos mais recentes do código : actions / checkout @ v2

      - nome : 📂 Os arquivos de sincronização
        usam : SamKirkland/FTP-Deploy-Action@4.1.0
        com :
          servidor : ftp.wedosvc.com.br
          nome de usuário : $ {{secrets.ftp_user}}
          senha : $ {{secrets.ftp_password}}