on : push
nome : 🚀 implantar servidor push
empregos :
  implantação na web :
    nome : 🎉 Implementar
    roda em : ubuntu-mais recente
    passos :
    - nome : 🚚 Obtenha o código mais recente
      usa : ações / checkout @ v2
    
    - nome : 📂 Sincronizar arquivos
      usa : SamKirkland/FTP-Deploy-Action@4.1.0
      com :
        servidor : $ {{secrets.ftp_host}}
        nome de usuário : $ {{secrets.ftp_user}}
        senha : $ {{secrets.ftp_password}}
